[package]
name = "supervisor-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["macros"] }
tokio-util = "0.7"

[dev-dependencies]
tokio = { version = "1.47", features = ["rt", "sync", "time"] }
