[package]
name = "supervisor-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3"
parking_lot = "0.12"
tokio = { version = "1.47", features = ["rt", "macros", "sync"] }

[dev-dependencies]
tokio = { version = "1.47", features = ["time"] }
